///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package test1

import (
	"fmt"
	"time"

	"github.com/a406299736/goframe/app/pkg/code"
	e "github.com/a406299736/goframe/pkg/errors"
	"github.com/a406299736/goframe/repository/dbrepo"

	"gorm.io/gorm"
)

func NewModel() *Test1 {
	return new(Test1)
}

func NewQueryBuilder() *Test1QueryBuilder {
	return new(Test1QueryBuilder)
}

func (t *Test1) Create(db *gorm.DB) (id int32, er e.Er) {
	if err := db.Create(t).Error; err != nil {
		return 0, e.NewErr(code.MySQLExecError, err.Error())
	}
	return t.Id, nil
}

type Test1QueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *Test1QueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *Test1QueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (er e.Er) {
	db = db.Model(&Test1{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err := db.Updates(m).Error; err != nil {
		return e.NewErr(code.MySQLExecError, err.Error())
	}
	return nil
}

func (qb *Test1QueryBuilder) Delete(db *gorm.DB) (er e.Er) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err := db.Delete(&Test1{}).Error; err != nil {
		return e.NewErr(code.MySQLExecError, err.Error())
	}
	return nil
}

func (qb *Test1QueryBuilder) Count(db *gorm.DB) (int64, e.Er) {
	var c int64
	res := qb.buildQuery(db).Model(&Test1{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return 0, e.NewErr(code.MySQLExecError, res.Error.Error())
	}
	return c, nil
}

func (qb *Test1QueryBuilder) First(db *gorm.DB) (*Test1, e.Er) {
	ret := &Test1{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return nil, e.NewErr(code.MySQLExecError, res.Error.Error())
	}
	return ret, nil
}

func (qb *Test1QueryBuilder) QueryOne(db *gorm.DB) (*Test1, e.Er) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *Test1QueryBuilder) QueryAll(db *gorm.DB) ([]*Test1, e.Er) {
	var ret []*Test1
	err := qb.buildQuery(db).Find(&ret).Error
	if err != nil {
		return nil, e.NewErr(code.MySQLExecError, err.Error())
	}
	return ret, nil
}

func (qb *Test1QueryBuilder) Limit(limit int) *Test1QueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *Test1QueryBuilder) Offset(offset int) *Test1QueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *Test1QueryBuilder) WhereId(p dbrepo.Predicate, value int32) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereIdIn(value []int32) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereIdNotIn(value []int32) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) OrderById(asc bool) *Test1QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *Test1QueryBuilder) WhereAspirations(p dbrepo.Predicate, value string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "aspirations", p),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereAspirationsIn(value []string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "aspirations", "IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereAspirationsNotIn(value []string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "aspirations", "NOT IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) OrderByAspirations(asc bool) *Test1QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "aspirations "+order)
	return qb
}

func (qb *Test1QueryBuilder) WhereMap(p dbrepo.Predicate, value string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "map", p),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereMapIn(value []string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "map", "IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereMapNotIn(value []string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "map", "NOT IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) OrderByMap(asc bool) *Test1QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "map "+order)
	return qb
}

func (qb *Test1QueryBuilder) WhereCall(p dbrepo.Predicate, value string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "call", p),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereCallIn(value []string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "call", "IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereCallNotIn(value []string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "call", "NOT IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) OrderByCall(asc bool) *Test1QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "call "+order)
	return qb
}

func (qb *Test1QueryBuilder) WhereRecruit(p dbrepo.Predicate, value string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "recruit", p),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereRecruitIn(value []string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "recruit", "IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereRecruitNotIn(value []string) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "recruit", "NOT IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) OrderByRecruit(asc bool) *Test1QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "recruit "+order)
	return qb
}

func (qb *Test1QueryBuilder) WhereUpdated(p dbrepo.Predicate, value time.Time) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated", p),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereUpdatedIn(value []time.Time) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated", "IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereUpdatedNotIn(value []time.Time) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated", "NOT IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) OrderByUpdated(asc bool) *Test1QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated "+order)
	return qb
}

func (qb *Test1QueryBuilder) WhereCreated(p dbrepo.Predicate, value time.Time) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created", p),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereCreatedIn(value []time.Time) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created", "IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) WhereCreatedNotIn(value []time.Time) *Test1QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created", "NOT IN"),
		value,
	})
	return qb
}

func (qb *Test1QueryBuilder) OrderByCreated(asc bool) *Test1QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created "+order)
	return qb
}
