[app]
  logpath="/usr/local/var/logs/"
  env="dev"

[hashids]
  length = 12
  secret = "6ab6122836cfef95f8db8"

[jwt]
  expireduration = 24
  secret = "ABC"

[language]
  local = "zh-cn"

[mysql]
  [mysql.base]
    connmaxlifetime = 60
    maxidleconn = 10
    maxopenconn = 100

  [mysql.read]
    addr = "127.0.0.1"
    name = "test1"
    pass = "root"
    user = "root"

  [mysql.write]
  addr = "127.0.0.1"
  name = "test1"
  pass = "root"
  user = "root"

  [mysql.conn1read]
    addr = "127.0.0.1"
    name = "test1"
    pass = "root"
    user = "root"

  [mysql.conn1write]
    addr = "127.0.0.1"
    name = "test1"
    pass = "root"
    user = "root"

[redis]
  addr = "127.0.0.1:6379"
  db = "0"
  maxretries = 3
  minidleconns = 5
  pass = ""
  poolsize = 10

[urltoken]
  expireduration = 10
  secret = "ABC"

[rocket]
  httpendpoint=""
  accesskey=""
  secretkey=""
  instanceid=""
  topic=""
  groupid=""

[center]
classUrl=""

[apollo]
appId="test"
cluster="default"
namespaceName="application"
ip="127.0.0.1"
